### PR TITLE
Add support for application/graphql-response+json

### LINKED ISSUE #14: Add support for application/graphql-response+json
[The preferred content type header for GraphQL server responses](https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md) is now `application/graphql-response+json`. The current content type header checks only support `application/json`, resulting in a _cant't parse response content_ error. The fix is pretty easy. I’ll have a pull request for this momentarily.

Love this tool, by the way. Gotten a lot of good use out of it over the last couple of years. Thanks for sharing it.

### PR DESCRIPTION
**Pull request by adamshaylor**
Resolves #14

### CODE REVIEW

**Review by bryceknz — APPROVED** [review]

**Review by kgpax — APPROVED** [review]

**Comment by kgpax** [comment]
@enkot would you be happy to merge this pretty trivial PR?  Newer GQL servers use this new response content type, and currently Querio opts to not parse or display the response from those servers.

**Comment by enkot** [comment]
@adamshaylor @kgpax @bryceknz 
Thanks for the PR! Really happy that someone is interested in improving Querio :)

**Insight:** I'm working on the next version based on: Vue 3, Typescript and Manifest V3. It will have simpler logic for parsing requests and more solid foundations for new features.

**Comment by bryceknz** [comment]
Thank you for merging this, @enkot! 🚀 Will you be publishing a new version to the chrome web store?

Very exciting news about the next version!! I'll be keeping an eye out for updates 🙌🏻

**Comment by enkot** [comment]
Submitted for review, should appear in the web store soon 👌

**Pull request merged**
